### ISSUE TITLE
PILLOW out of date

### ISSUE THREAD

**Issue by iplayfast** [m87-labs/moondream#28]
I'm getting errors relating to PILLOW, it seems you are using an old version as PILLOW_VERSION has been discontinued. 

```
python sample.py 
Traceback (most recent call last):
  File "/home/chris/ai/moondream/sample.py", line 1, in <module>
    from moondream import VisionEncoder, TextModel
  File "/home/chris/ai/moondream/moondream/__init__.py", line 1, in <module>
    from .vision_encoder import VisionEncoder
  File "/home/chris/ai/moondream/moondream/vision_encoder.py", line 4, in <module>
    from torchvision.transforms.v2 import (
  File "/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/chris/anaconda3/envs/whisper/lib/python3.12/site-packages/PIL/__init__.py)
```

**Comment by KPCOFGS** [comment]
I am using `pillow==10.2.0`, try this version and see if it solves the problem
