### ISSUE TITLE
ModuleNotFoundError: No module named 'moondream'

### ISSUE THREAD

**Issue by junaid3d** [m87-labs/moondream#38]
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

D:\AI\mdr>python -m venv moondr

D:\AI\mdr>cd moondr

D:\AI\mdr\moondr>cd scripts

D:\AI\mdr\moondr\Scripts>activate.bat

(moondr) D:\AI\mdr\moondr\Scripts>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Downloading https://download.pytorch.org/whl/cu118/torch-2.2.0%2Bcu118-cp310-cp310-win_amd64.whl (2704.3 MB)
     ---------------------------------------- 2.7/2.7 GB 380.5 kB/s eta 0:00:00
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.17.0%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.2.0%2Bcu118-cp310-cp310-win_amd64.whl (4.0 MB)
Collecting networkx
  Downloading https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 14.9 MB/s eta 0:00:00
Collecting filelock
  Using cached https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting fsspec
  Using cached https://download.pytorch.org/whl/fsspec-2023.4.0-py3-none-any.whl (153 kB)
Collecting typing-extensions>=4.8.0
  Using cached https://download.pytorch.org/whl/typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Downloading https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 12.9 MB/s eta 0:00:00
Collecting numpy
  Downloading https://download.pytorch.org/whl/numpy-1.26.3-cp310-cp310-win_amd64.whl (15.8 MB)
     ---------------------------------------- 15.8/15.8 MB 11.5 MB/s eta 0:00:00
Collecting requests
  Using cached https://download.pytorch.org/whl/requests-2.28.1-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached https://download.pytorch.org/whl/urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<3,>=2
  Using cached https://download.pytorch.org/whl/charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torchaudio
Successfully installed MarkupSafe-2.1.3 certifi-2022.12.7 charset-normalizer-2.1.1 filelock-3.9.0 fsspec-2023.4.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.3 pillow-10.2.0 requests-2.28.1 sympy-1.12 torch-2.2.0+cu118 torchaudio-2.2.0+cu118 torchvision-0.17.0+cu118 typing-extensions-4.8.0 urllib3-1.26.13

(moondr) D:\AI\mdr\moondr\Scripts>cd..

(moondr) D:\AI\mdr\moondr>cd git

(moondr) D:\AI\mdr\moondr\git>pip install -r requirements.txt
Collecting accelerate==0.25.0
  Using cached accelerate-0.25.0-py3-none-any.whl (265 kB)
Collecting huggingface-hub==0.20.1
  Using cached huggingface_hub-0.20.1-py3-none-any.whl (330 kB)
Collecting Pillow==10.1.0
  Using cached Pillow-10.1.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting torch==2.1.2
  Using cached torch-2.1.2-cp310-cp310-win_amd64.whl (192.3 MB)
Collecting torchvision==0.16.2
  Using cached torchvision-0.16.2-cp310-cp310-win_amd64.whl (1.1 MB)
Collecting transformers==4.36.2
  Using cached transformers-4.36.2-py3-none-any.whl (8.2 MB)
Collecting einops==0.7.0
  Using cached einops-0.7.0-py3-none-any.whl (44 kB)
Collecting gradio==4.15.0
  Using cached gradio-4.15.0-py3-none-any.whl (16.6 MB)
Collecting timm==0.9.12
  Using cached timm-0.9.12-py3-none-any.whl (2.2 MB)
Collecting safetensors>=0.3.1
  Using cached safetensors-0.4.2-cp310-none-win_amd64.whl (269 kB)
Requirement already satisfied: numpy>=1.17 in d:\ai\mdr\moondr\lib\site-packages (from accelerate==0.25.0->-r requirements.txt (line 1)) (1.26.3)
Collecting psutil
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
Collecting packaging>=20.0
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting tqdm>=4.42.1
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Requirement already satisfied: requests in d:\ai\mdr\moondr\lib\site-packages (from huggingface-hub==0.20.1->-r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\ai\mdr\moondr\lib\site-packages (from huggingface-hub==0.20.1->-r requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: filelock in d:\ai\mdr\moondr\lib\site-packages (from huggingface-hub==0.20.1->-r requirements.txt (line 2)) (3.9.0)
Collecting fsspec>=2023.5.0
  Using cached fsspec-2023.12.2-py3-none-any.whl (168 kB)
Requirement already satisfied: sympy in d:\ai\mdr\moondr\lib\site-packages (from torch==2.1.2->-r requirements.txt (line 4)) (1.12)
Requirement already satisfied: jinja2 in d:\ai\mdr\moondr\lib\site-packages (from torch==2.1.2->-r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: networkx in d:\ai\mdr\moondr\lib\site-packages (from torch==2.1.2->-r requirements.txt (line 4)) (3.2.1)
Collecting tokenizers<0.19,>=0.14
  Using cached tokenizers-0.15.1-cp310-none-win_amd64.whl (2.2 MB)
Collecting regex!=2019.12.17
  Using cached regex-2023.12.25-cp310-cp310-win_amd64.whl (269 kB)
Requirement already satisfied: markupsafe~=2.0 in d:\ai\mdr\moondr\lib\site-packages (from gradio==4.15.0->-r requirements.txt (line 8)) (2.1.3)
Collecting orjson~=3.0
  Using cached orjson-3.9.12-cp310-none-win_amd64.whl (134 kB)
Collecting ffmpy
  Using cached ffmpy-0.3.1-py3-none-any.whl
Collecting python-multipart
  Using cached python_multipart-0.0.6-py3-none-any.whl (45 kB)
Collecting typer[all]<1.0,>=0.9
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Collecting altair<6.0,>=4.2.0
  Using cached altair-5.2.0-py3-none-any.whl (996 kB)
Collecting ruff>=0.1.7
  Downloading ruff-0.1.15-py3-none-win_amd64.whl (7.3 MB)
     ---------------------------------------- 7.3/7.3 MB 10.0 MB/s eta 0:00:00
Collecting httpx
  Using cached httpx-0.26.0-py3-none-any.whl (75 kB)
Collecting pandas<3.0,>=1.0
  Using cached pandas-2.2.0-cp310-cp310-win_amd64.whl (11.6 MB)
Collecting pydantic>=2.0
  Using cached pydantic-2.6.0-py3-none-any.whl (394 kB)
Collecting importlib-resources<7.0,>=1.3
  Using cached importlib_resources-6.1.1-py3-none-any.whl (33 kB)
Collecting fastapi
  Using cached fastapi-0.109.0-py3-none-any.whl (92 kB)
Collecting gradio-client==0.8.1
  Using cached gradio_client-0.8.1-py3-none-any.whl (305 kB)
Collecting matplotlib~=3.0
  Using cached matplotlib-3.8.2-cp310-cp310-win_amd64.whl (7.6 MB)
Collecting tomlkit==0.12.0
  Using cached tomlkit-0.12.0-py3-none-any.whl (37 kB)
Collecting aiofiles<24.0,>=22.0
  Using cached aiofiles-23.2.1-py3-none-any.whl (15 kB)
Collecting pydub
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting uvicorn>=0.14.0
  Downloading uvicorn-0.27.0.post1-py3-none-any.whl (60 kB)
     ---------------------------------------- 60.7/60.7 kB 3.2 MB/s eta 0:00:00
Collecting semantic-version~=2.0
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting websockets<12.0,>=10.0
  Using cached websockets-11.0.3-cp310-cp310-win_amd64.whl (124 kB)
Collecting toolz
  Using cached toolz-0.12.1-py3-none-any.whl (56 kB)
Collecting jsonschema>=3.0
  Using cached jsonschema-4.21.1-py3-none-any.whl (85 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.47.2-cp310-cp310-win_amd64.whl (2.2 MB)
Collecting pyparsing>=2.3.1
  Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.2.0-cp310-cp310-win_amd64.whl (186 kB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.3.1
  Using cached kiwisolver-1.4.5-cp310-cp310-win_amd64.whl (56 kB)
Collecting pytz>=2020.1
  Using cached pytz-2023.4-py2.py3-none-any.whl (506 kB)
Collecting tzdata>=2022.7
  Using cached tzdata-2023.4-py2.py3-none-any.whl (346 kB)
Collecting pydantic-core==2.16.1
  Using cached pydantic_core-2.16.1-cp310-none-win_amd64.whl (1.9 MB)
Collecting annotated-types>=0.4.0
  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting click<9.0.0,>=7.1.1
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting shellingham<2.0.0,>=1.3.0
  Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting rich<14.0.0,>=10.11.0
  Using cached rich-13.7.0-py3-none-any.whl (240 kB)
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting starlette<0.36.0,>=0.35.0
  Using cached starlette-0.35.1-py3-none-any.whl (71 kB)
Requirement already satisfied: certifi in d:\ai\mdr\moondr\lib\site-packages (from httpx->gradio==4.15.0->-r requirements.txt (line 8)) (2022.12.7)
Requirement already satisfied: idna in d:\ai\mdr\moondr\lib\site-packages (from httpx->gradio==4.15.0->-r requirements.txt (line 8)) (3.4)
Collecting anyio
  Using cached anyio-4.2.0-py3-none-any.whl (85 kB)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting httpcore==1.*
  Using cached httpcore-1.0.2-py3-none-any.whl (76 kB)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\ai\mdr\moondr\lib\site-packages (from requests->huggingface-hub==0.20.1->-r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\ai\mdr\moondr\lib\site-packages (from requests->huggingface-hub==0.20.1->-r requirements.txt (line 2)) (1.26.13)
Requirement already satisfied: mpmath>=0.19 in d:\ai\mdr\moondr\lib\site-packages (from sympy->torch==2.1.2->-r requirements.txt (line 4)) (1.3.0)
Collecting rpds-py>=0.7.1
  Using cached rpds_py-0.17.1-cp310-none-win_amd64.whl (205 kB)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4
  Downloading referencing-0.33.0-py3-none-any.whl (26 kB)
Collecting attrs>=22.2.0
  Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0
  Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Collecting exceptiongroup>=1.0.2
  Using cached exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, pydub, ffmpy, websockets, tzdata, toolz, tomlkit, sniffio, six, shellingham, semantic-version, safetensors, ruff, rpds-py, regex, pyyaml, python-multipart, pyparsing, pygments, pydantic-core, psutil, Pillow, packaging, orjson, mdurl, kiwisolver, importlib-resources, h11, fsspec, fonttools, exceptiongroup, einops, cycler, contourpy, colorama, attrs, annotated-types, aiofiles, tqdm, torch, referencing, python-dateutil, pydantic, markdown-it-py, httpcore, click, anyio, uvicorn, typer, torchvision, starlette, rich, pandas, matplotlib, jsonschema-specifications, huggingface-hub, httpx, tokenizers, timm, jsonschema, gradio-client, fastapi, accelerate, transformers, altair, gradio
  Attempting uninstall: Pillow
    Found existing installation: pillow 10.2.0
    Uninstalling pillow-10.2.0:
      Successfully uninstalled pillow-10.2.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: torch
    Found existing installation: torch 2.2.0+cu118
    Uninstalling torch-2.2.0+cu118:
      Successfully uninstalled torch-2.2.0+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.17.0+cu118
    Uninstalling torchvision-0.17.0+cu118:
      Successfully uninstalled torchvision-0.17.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.0+cu118 requires torch==2.2.0+cu118, but you have torch 2.1.2 which is incompatible.
Successfully installed Pillow-10.1.0 accelerate-0.25.0 aiofiles-23.2.1 altair-5.2.0 annotated-types-0.6.0 anyio-4.2.0 attrs-23.2.0 click-8.1.7 colorama-0.4.6 contourpy-1.2.0 cycler-0.12.1 einops-0.7.0 exceptiongroup-1.2.0 fastapi-0.109.0 ffmpy-0.3.1 fonttools-4.47.2 fsspec-2023.12.2 gradio-4.15.0 gradio-client-0.8.1 h11-0.14.0 httpcore-1.0.2 httpx-0.26.0 huggingface-hub-0.20.1 importlib-resources-6.1.1 jsonschema-4.21.1 jsonschema-specifications-2023.12.1 kiwisolver-1.4.5 markdown-it-py-3.0.0 matplotlib-3.8.2 mdurl-0.1.2 orjson-3.9.12 packaging-23.2 pandas-2.2.0 psutil-5.9.8 pydantic-2.6.0 pydantic-core-2.16.1 pydub-0.25.1 pygments-2.17.2 pyparsing-3.1.1 python-dateutil-2.8.2 python-multipart-0.0.6 pytz-2023.4 pyyaml-6.0.1 referencing-0.33.0 regex-2023.12.25 rich-13.7.0 rpds-py-0.17.1 ruff-0.1.15 safetensors-0.4.2 semantic-version-2.10.0 shellingham-1.5.4 six-1.16.0 sniffio-1.3.0 starlette-0.35.1 timm-0.9.12 tokenizers-0.15.1 tomlkit-0.12.0 toolz-0.12.1 torch-2.1.2 torchvision-0.16.2 tqdm-4.66.1 transformers-4.36.2 typer-0.9.0 tzdata-2023.4 uvicorn-0.27.0.post1 websockets-11.0.3

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(moondr) D:\AI\mdr\moondr\git>python gradio_demo.py
Traceback (most recent call last):
  File "D:\AI\mdr\moondr\git\gradio_demo.py", line 4, in <module>
    from moondream import Moondream, detect_device
ModuleNotFoundError: No module named 'moondream'

**Comment by junaid3d** [comment]
`(moondr) D:\AI\mdr\moondr\git>python gradio_demo.py
Traceback (most recent call last):
  File "D:\AI\mdr\moondr\git\gradio_demo.py", line 4, in <module>
    from moondream import Moondream, detect_device
ModuleNotFoundError: No module named 'moondream'`

**Comment by KPCOFGS** [comment]
Does the path `D:\AI\mdr\moondr\git\moondream\` exist?
