### ISSUE TITLE
Tensor size mismatch

### ISSUE THREAD

**Issue by JohnnyStreet** [m87-labs/moondream#50]
The expanded size of the tensor (754) must match the existing size (755) at non-singleton dimension 1.  Target sizes: [1, 754].  Tensor sizes: [1, 755]

```
        tokenizer = Tokenizer.from_pretrained(model_id)
        moondream = Moondream.from_pretrained(model_id).to(
            device=device, dtype=dtype
        )
```
...
```
async def vision(
    image: UploadFile = File(...),
    prompt: str = "Describe the image in a few words.",
):
    try:
        img = Image.open(io.BytesIO(image.file.read()))
        moondream: Moondream = plugin.resources["moondream"]
        tokenizer: Tokenizer = plugin.resources["tokenizer"]
        print("Encoding image...")
        image_embeds = moondream.encode_image(img)
        print("Getting response...")
        response = moondream.answer_question(image_embeds, prompt, tokenizer)

        ...
```

It gets through the image encoding step but fails on the response. I have tried this with lots of images, mostly 512x512 or 786x786 but also some other odd sizes.

**Comment by vikhyat** [comment]
Does it return a stack trace? Would help to know which operation is causing the failure.

**Comment by JohnnyStreet** [comment]
```
[2024-02-24 13:28:32] The expanded size of the tensor (754) must match the existing size (755) at non-singleton dimension 1.  Target sizes: [1, 754].  Tensor sizes: [1, 755]
Traceback (most recent call last):
  File "C:\my-project\plugins\vision.py", line 65, in vision
    response = moondream.answer_question(image_embeds, prompt, tokenizer)
  File "C:\my-project\submodules\moondream\moondream\moondream.py", line 93, in answer_question
    answer = self.generate(
  File "C:\my-project\submodules\moondream\moondream\moondream.py", line 77, in generate
    output_ids = self.text_model.generate(
  File "c:\my-project\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\transformers\generation\utils.py", line 1544, in generate
    return self.greedy_search(
  File "c:\my-project\venv\lib\site-packages\transformers\generation\utils.py", line 2404, in greedy_search
    outputs = self(
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 709, in forward
    hidden_states = self.transformer(
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 675, in forward
    else func(*args)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 541, in forward
    attn_outputs = self.mixer(
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 514, in forward
    attn_output_function(x, past_key_values, attention_mask)
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 494, in _forward_cross_attn
    return attn_func(
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 491, in <lambda>
    else lambda fn, *args, **kwargs: fn(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "c:\my-project\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\my-project\submodules\moondream\moondream\modeling_phi.py", line 318, in forward
    padding_mask.masked_fill_(key_padding_mask, 0.0)
RuntimeError: The expanded size of the tensor (754) must match the existing size (755) at non-singleton dimension 1.  Target sizes: [1, 754].  Tensor sizes: [1, 755]
```

**Comment by chenjunzeshen** [comment]
Maybe it's a version issue，I also encountered similar errors at the beginning，After reinstalling the package according to the requirements.txt file, the issue was resolved

**Comment by JohnnyStreet** [comment]
> Maybe it's a version issue

I'm afraid this is likely the case, as I am on a source branch of diffusers. I'm sure it works alone and there are old commits that still work on my setup. Still trying to narrow down what is being done differently now. Maybe there was an off-by-one error either introduced or corrected in the branch of diffusers I am using (diffusers-yield-callback, which was the most up-to-date branch I could find that contained Cascade pipelines).

**Comment by Karlzzb** [comment]
I had similar issue. Fix it after changing the transformers version from 4.38.1 to 4.36.2.

**Comment by ricperry** [comment]
Downgrading to 4.36.2 isn't a very good solution as that means other programs/libraries break in the venv. Is there a tweak to the modeling_phi.py file that would fix this?

**Comment by JohnnyStreet** [comment]
> Is there a tweak to the modeling_phi.py file that would fix this?

Starting at line 311 for reference:
```
        if key_padding_mask is not None:
            padding_mask = torch.full(
                (batch_size, seqlen_k),
                -10000.0,
                dtype=scores.dtype,
                device=scores.device,
            )

            # ADD THE FOLLOWING SINGLE LINE OF CODE
            key_padding_mask = key_padding_mask[:, :seqlen_k]
            
            padding_mask.masked_fill_(key_padding_mask, 0.0)
            scores = scores + rearrange(padding_mask, "b s -> b 1 1 s")
```

This does not get to the bottom of why key_padding_mask  is the wrong length to begin with but it works.

**Comment by 311-code** [comment]
The fix above me by Johnnystreet worked for me, I had mutiple modeling_phi.py files, and used the one under` C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6ebunchofcharacters`

I was trying to use this workflow https://comfyworkflows.com/workflows/b703fa8b-5fe0-4678-8692-021766a891c4 and followed the instructions in the beginning of [this video](https://www.youtube.com/watch?v=Q9y-7Nwj2ic) but originally didn't work.

Here is the modified code again pasted at line 311:
```
        if key_padding_mask is not None:
            padding_mask = torch.full(
                (batch_size, seqlen_k),
                -10000.0,
                dtype=scores.dtype,
                device=scores.device,
            )
            key_padding_mask = key_padding_mask[:, :seqlen_k]
            padding_mask.masked_fill_(key_padding_mask, 0.0)
            scores = scores + rearrange(padding_mask, "b s -> b 1 1 s")
```

Original Error: 

```
Error occurred when executing Moondream Interrogator (NO COMMERCIAL USE):

The size of tensor a (760) must match the size of tensor b (761) at non-singleton dimension 1

  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hangover-Moondream\ho_moondream.py", line 71, in interrogate
    answer = self.model.answer_question(enc_image, prompt, self.tokenizer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\moondream.py", line 93, in answer_question
    answer = self.generate(
             ^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\moondream.py", line 77, in generate
    output_ids = self.text_model.generate(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 1544, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 2404, in greedy_search
    outputs = self(
              ^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 709, in forward
    hidden_states = self.transformer(
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 675, in forward
    else func(*args)
         ^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 541, in forward
    attn_outputs = self.mixer(
                   ^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 514, in forward
    attn_output_function(x, past_key_values, attention_mask)
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 494, in _forward_cross_attn
    return attn_func(
           ^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 491, in 
    else lambda fn, *args, **kwargs: fn(*args, **kwargs)
                                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NewPC\.cache\huggingface\modules\transformers_modules\vikhyatk\moondream1\f6e9da68e8f1b78b8f3ee10905d56826db7a5802\modeling_phi.py", line 318, in forward
    padding_mask.masked_fill_(key_padding_mask, 0.0)
Queue size: 0
Extra options
```

**Comment by vikhyat** [comment]
Will dig in and get it sorted out later tonight!

**Comment by 311-code** [comment]
I just updated my comment, it works after I tried his code out.

**Comment by vikhyat** [comment]
Looks like the regression was introduced between transformers versions 4.37.2 and 4.38.0.

**Comment by vikhyat** [comment]
Should be fixed now: https://github.com/vikhyat/moondream/commit/1061fbf9c7e301ca18b716651dc388e48c2390a8
