### ISSUE TITLE
unknown model

### ISSUE THREAD

**Issue by Asianfleet** [m87-labs/moondream#64]
(main) (base) legion4080@LAPTOP-DTSSV3S1:~/MYXY/AI_pkgs/moondream$ python gradio_demo.py
Using device: cuda
If you run into issues, pass the `--cpu` flag to this script.

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/legion4080/MYXY/AI_pkgs/moondream/gradio_demo.py", line 25, in <module>
    moondream = AutoModelForCausalLM.from_pretrained(
  File "/home/legion4080/anaconda3/envs/main/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/home/legion4080/anaconda3/envs/main/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3375, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/legion4080/.cache/huggingface/modules/transformers_modules/moondream2/moondream.py", line 16, in __init__
    self.vision_encoder = VisionEncoder()
  File "/home/legion4080/.cache/huggingface/modules/transformers_modules/moondream2/vision_encoder.py", line 98, in __init__
    VisualHolder(timm.create_model("vit_so400m_patch14_siglip_384"))
  File "/home/legion4080/anaconda3/envs/main/lib/python3.9/site-packages/timm/models/factory.py", line 78, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (vit_so400m_patch14_siglip_384)

**Comment by vikhyat** [comment]
Looks like you have an old version of timm. Try `pip install -U timm`

**Comment by T8star1984** [comment]
I have same question,and I try to update "timm",but it also report same error

**Comment by ProGamerGov** [comment]
@T8star1984 Try making a new conda instance and install the requirements.txt from this repo. That's how I solved this issue

**Comment by Asianfleet** [comment]
Thanks！i'll have a try.

**Comment by vikhyat** [comment]
Going to close this and use #65 as the tracking issue.
