### ISSUE TITLE
torchvision error ？？？(IMPORT FAILED) moondream plugin

### ISSUE THREAD

**Issue by kryfo** [m87-labs/moondream#70]
Traceback (most recent call last):
  File "E:\StableDiffusion-ComfyUI\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\StableDiffusion-ComfyUI\ComfyUI\custom_nodes\Comfyui_image2prompt\__init__.py", line 40, in <module>
    from .image2text import Image2Text, LoadImage2TextModel, Image2TextWithTags
  File "E:\StableDiffusion-ComfyUI\ComfyUI\custom_nodes\Comfyui_image2prompt\image2text.py", line 1, in <module>
    from .moondream_model import MoondreamModel
  File "E:\StableDiffusion-ComfyUI\ComfyUI\custom_nodes\Comfyui_image2prompt\moondream_model.py", line 8, in <module>
    from torchvision.transforms.v2 import (
ImportError: cannot import name 'ToImage' from 'torchvision.transforms.v2' (E:\StableDiffusion-ComfyUI\python_embeded\lib\site-packages\torchvision\transforms\v2\__init__.py)

Cannot import E:\StableDiffusion-ComfyUI\ComfyUI\custom_nodes\Comfyui_image2prompt module for custom nodes: cannot import name 'ToImage' from 'torchvision.transforms.v2' (E:\StableDiffusion-ComfyUI\python_embeded\lib\site-packages\torchvision\transforms\v2\__init__.py)

**Comment by Asianfleet** [comment]
I think you should check the version of torch.My version is 2.1.0

**Comment by harsham05** [comment]
```pip3 install torchvision```
worked for me

**Comment by kryfo** [comment]
> I think you should check the version of torch.My version is 2.1.0

Yes, I solved the problem after updated
